<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Cicle Staging Mobile App - Board</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bce237f2-f67c-4ab9-b65a-0fe6f175abbf</testSuiteGuid>
   <testCaseLink>
      <guid>9caceee3-2527-48f4-a989-31adb52a3d0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Board/TC_Board_CS-02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9a2221b-18c8-4f5f-a2bb-aef7f8ed37d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0b73059-4b92-4ca2-b8ca-258d4076ba24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Board/TC_Board_CS-03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>70351d86-2261-4bde-baf1-2b7fdc3b8d00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Board/TC_Board_CS-04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>dde4a945-f84e-4bda-9f61-1a80c5013493</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Board/TC_Board_CS-05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>08e817f7-7dd3-49fb-9b92-ff22f5bbc93e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Board/TC_Board_CS-06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09d59eb7-40db-4756-af27-fae0a35c40c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dadec5da-5032-4318-8fc0-3b33fcc6543e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96c76c70-c8d9-47ac-b96f-2d92ba99e7a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68f8c949-1d1e-42a6-992c-333aa950ef5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Board/TC_Board_CS-07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc88470a-eb77-4aff-b17c-e254bd831edb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a808ea1c-bd72-4b97-b96a-c06c145b36ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Board/TC_Board_CS-08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66e476d8-57be-4a27-9a5b-dcb133a0f9e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>841ef619-4808-4a11-b3a9-9956f9fa3c6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Board/TC_Board_CS-09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>89a60a9d-e810-468e-a65c-76825f33116b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Board/TC_Board_CS-10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00dfb058-9e65-4f55-9458-b87e32eb92b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8bd2396-484f-4e8d-8451-415f36242605</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Board/TC_Board_CS-11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b8d490c-54fd-4df7-82e7-d06d2240028b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c857b7fe-2919-48f7-a905-f9eb40674142</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Board/TC_Board_CS-12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7a93a51-306f-4cc0-bafc-4c8e7b02b2a3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
